FROM registry.redhat.io/ubi7/ubi:7.6
MAINTAINER IBM zxpanbj@cn.ibm.com

ARG arch
ARG redhare_version
ARG redhare_top=/opt/dlim
ARG redhare_instance_name=msd
ARG release_build
ARG port=9080
ARG umask=022
ARG MSD_FILE_NAME
ARG MSD_USER
ARG MSD_UID

LABEL name="Watson Machine Learning Accelerator MSD" \
      vendor="IBM" \
      version=$redhare_version \
      release=$release_build \
      description="The MSD image for Watson Machine Learning Accelerator." \
      summary="WML-A MSD"

# TODO: Include a license and place it in the /licenses directory.

ENV REDHARE_IS_K8S=ON \
    RELEASE_BUILD=$release_build \
    REDHARE_TOP=$redhare_top \
    REDHARE_VERSION=$redhare_version \
    REDHARE_BINARY_TYPE=linux-$arch \
    REDHARE_INSTANCE_NAME=$redhare_instance_name \
    REDHARE_ETC_PATH=$redhare_top/$redhare_version/linux-$arch/etc/ \
    LD_LIBRARY_PATH=$redhare_top/$redhare_version/linux-$arch/lib:${LD_LIBRARY_PATH} \
    Umask=$umask \
    PYTHONPATH=$redhare_top/$redhare_version/linux-$arch/lib:${PYTHONPATH} \
    PATH=$redhare_top/$redhare_version/linux-$arch/etc:${PATH}

RUN yum -y update && \
    yum clean all && \
    yum install -y libtool openssl-devel libuuid-devel bind-utils && \
    yum clean all && rm -rf /var/cache/yum/* && \
    mkdir -p $redhare_top/$redhare_version/linux-$arch/etc && \
    mkdir -p $redhare_top/$redhare_version/linux-$arch/lib && \
    mkdir -p $redhare_top/conf/$redhare_instance_name && \
    mkdir -p $redhare_top/logs && \
    mkdir -p $redhare_top/work && \
    touch $redhare_top/conf/dlim.conf && \
    touch $redhare_top/conf/$redhare_instance_name/msd.conf && \

    sed -i -e 's/^PASS_MIN_LEN.*/PASS_MIN_LEN    8/' /etc/login.defs && \
    sed -i 's/^PASS_MAX_DAYS.*/PASS_MAX_DAYS   90/' /etc/login.defs && \
    sed -i 's/^PASS_MIN_DAYS.*/PASS_MIN_DAYS   1/' /etc/login.defs && \
    sed -i 's/^# minlen.*/minlen= 9/' /etc/security/pwquality.conf && \

    curl -o mss.tar.gz -f -X GET "${HTTP_PROXY}/${MSD_FILE_NAME}" && \
    tar xvzf mss.tar.gz && \
    cp -r redhare/$redhare_version/linux-$arch/etc/msd $redhare_top/$redhare_version/linux-$arch/etc && \
    cp -r redhare/$redhare_version/linux-$arch/lib $redhare_top/$redhare_version/linux-$arch/ && \
    cp -r redhare/$redhare_version/schema $redhare_top/$redhare_version/ && \
    rm -rf mss.tar.gz redhare

RUN useradd -m -s /bin/bash -u $MSD_UID $MSD_USER && \
    chown -R $MSD_USER:$MSD_UID $REDHARE_TOP

WORKDIR $redhare_top/work

USER $MSD_USER

EXPOSE $port
CMD ["msd"]
